build:
  image: default-bionic
  environment:
    php: 8.1

checks:
  php: true

coding_style:
  php:
    spaces:
      before_parentheses:
        closure_definition: true
      around_operators:
        concatenation: true
        negation: true
      other:
        after_type_cast: true

tools:
  external_code_coverage: true

  php_code_sniffer:
    config:
      standard: "PSR2"

filter:
  excluded_paths:
    - tests/*
