name: "Tests"

on: [push, pull_request]

jobs:
  phpunit:
    name: "Tests"
    runs-on: "ubuntu-22.04"

    strategy:
      matrix:
        php-version:
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
        deps:
          - "lowest"
          - "highest"
        coverage:
          - "false"
        include:
          - deps: "highest"
            php-version: "8.1"
            coverage: "true"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "pcov"
          ini-values: "zend.assertions=1"
      - name: "Install dependencies"
        uses: ramsey/composer-install@v1
        with:
          dependency-versions: ${{ matrix.deps }}
          composer-options: --prefer-dist
      - name: "Run PHPUnit"
        run: "vendor/bin/phpunit"
        if: "${{ matrix.coverage != 'true' }}"
      - name: "Run PHPUnit with coverage"
        run: "vendor/bin/phpunit --coverage-clover=coverage.xml"
      - name: "Run PHP-CS-Fixer (E2E test)"
        run: "vendor/bin/php-cs-fixer fix --dry-run --diff"
        if: "${{ matrix.deps != 'lowest' && matrix.php-version != '8.1' }}"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 10
      - name: Upload Scrutinizer coverage
        if: "${{ matrix.deps == 'highest' && matrix.php-version == '8.1' && matrix.coverage == 'true' }}"
        uses: sudo-bot/action-scrutinizer@latest
        coverage-file: "coverage.xml"
